language: ruby

rvm:
  - 1.9.3
  - 2.1.1
  - 2.2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile

services:
  - mongodb

env: CI="travis"

script: "bundle exec rspec"

sudo: false